export * from "./pages/Otp"
export * from "./pages/Welcome"
export * from "./pages/Otp"
export * from "./pages/Test"
export * from "./pages/Newsletter"
export * from "./pages/Verification"
export * from "./pages/EventInvitation"